### ISSUE TITLE
bundle_jbrowse installation errors

### ISSUE THREAD

**Issue by ialarmedalien** [galaxyproject/tools-iuc#1101]
After updating Galaxy to 16.10 and JBrowse to the latest version from the toolshed, I'm getting the following errors with `bundle_jbrowse`:

**Tool shed repository:**
package_perl_bundle_jbrowse_1_12_0
**Tool shed repository changeset revision:**
52153ec17769
**Tool dependency status:**
Error
**Tool dependency installation error:**

> `Attempt to reload Scalar/Util.pm aborted. Compilation failed in require at /global/homes/a/aireland/perl5/lib/perl5/File/Temp.pm line 18. BEGIN failed--compilation aborted at /global/homes/a/aireland/perl5/lib/perl5/File/Temp.pm line 18. Compilation failed in require at /global/homes/a/aireland/perl5/lib/perl5/Capture/Tiny.pm line 11. BEGIN failed--compilation aborted at /global/homes/a/aireland/perl5/lib/perl5/Capture/Tiny.pm line 11. Compilation failed in require at (eval 28) line 1. BEGIN failed--compilation aborted at Makefile.PL line 51.
`

The installation log is attached. I'm not sure if my local perl installation is interfering with the one that Galaxy is trying to install, given that the path mentioned in the errors above is `/global/homes/a/aireland/perl5/lib/perl5/`, rather than the Galaxy perl path, i.e. `/global/homes/a/aireland/galaxy/tool_dependencies/perl/5.18.1/iuc/package_perl_5_18/35f117d7396b/`.

[errs.txt](https://github.com/galaxyproject/tools-iuc/files/685920/errs.txt)

**Comment by erasche** [comment]
- Would you mind just trying to re-install the package? That sometimes fixes these sorts of issues.
- Ah, that's not great that it's accessing the user environment rather than toolshed dependencies only, but it has been a long time since I've touched package installation, not sure what is normal there.
- I'm afraid I don't have time to look into this right now, I'm not sure when I'll be able to help. Perhaps some other IUC member has comments.

**Comment by abretaud** [comment]
Oh, I missed this issue
If you have the possibility, I would suggest trying to use the conda resolver, with the latest changes to the jbrowse tools it should work better

**Comment by ialarmedalien** [comment]
I updated Galaxy to 17.01 and switched to conda, and all my JBrowse issues magically disappeared!

**Comment by bgruening** [comment]
@ialarmedalien more of these news :)
